#!/bin/zsh
set -eux


ARCH='arm64'



# CUSTOMIZE TERMINAL

echo '# custom prompt' > ~/.zshrc
echo 'PS1="%3~ $ "\n' >> ~/.zshrc



# FINDER SETTINGS

defaults write com.apple.Finder AppleShowAllFiles true



# INSTALL HOMEBREW

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew update

# these lines are dependent on where homebrew is located, location changes depending on arch (intel vs arm)
: "${BREW_PATH:=/opt/homebrew/bin/brew}"
brew_activate=$(printf 'eval $(%s shellenv)' ${BREW_PATH})
echo '# activate brew' >> ~/.zshrc
echo "${brew_activate}\n" >> ~/.zshrc
source ~/.zshrc



# ADD GNU/LINUX UTILS

temp_dir=$(mktemp -d)
git clone https://github.com/fabiomaia/linuxify.git "${temp_dir}" && cd "${temp_dir}" && ./linuxify install
rm -rf "${temp_dir}"
echo '# gnu/linux util paths' >> ~/.zshrc
echo ". ~/.linuxify\n" >> ~/.zshrc
source ~/.zshrc



# CONFIGURE VIM

cd ~ && wget https://gist.githubusercontent.com/adriansahlman/1068fbc6b5b7fd80ea62bcc1b3de0275/raw/1a5e5a3cacbf95edcae89146db0e65a2a0b2f3af/.vimrc



# ADD GO

brew install go
go install github.com/segmentio/golines@latest



# ADD COMMON APPS

brew install --cask firefox
brew install --cask spotify
brew install --cask vlc
brew install --cask slack
brew install --cask clickup
brew install --cask discord
brew install --cask visual-studio-code
brew install --cask docker

# Install protoc
PROTOC_ZIP=protoc-3.14.0-osx-x86_64.zip
curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.14.0/$PROTOC_ZIP
sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc
sudo unzip -o $PROTOC_ZIP -d /usr/local 'include/*'
rm -f $PROTOC_ZIP
sudo chmod +x /usr/local/bin/protoc



# VSCODE SETUP

# disable key hold functionality
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# install neovim
brew install neovim

# add neovim conifg
mkdir -p ~/.config/nvim
cd ~/.config/nvim && wget https://gist.githubusercontent.com/adriansahlman/8982f99b770d5972bf470f5ba2a4ed06/raw/07c776587c5932ab87b1c154788e6a25e960739c/init.vim

# install neovim plugin manager
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# install neovim plugins
nvim -c ':PlugInstall' -c ':q' -c ':q'



# CONFIGURE GIT

git config --global init.defaultBranch main

git config --global user.name "Adrian Sahlman"
git config --global user.email "adrian.sahlman@gmail.com"
git config --global core.editor vim



# ADD PYTHON

PYTHON_VERSION=3.8
curl -fsSL -v -o ~/miniconda.sh -O  "https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-${ARCH}.sh"
chmod +x ~/miniconda.sh
~/miniconda.sh -b -p ~/anaconda3
rm ~/miniconda.sh
~/anaconda3/bin/conda install -y python=${PYTHON_VERSION} cmake conda-build pyyaml numpy ipython
echo 'export PATH="~/anaconda3/bin:${PATH}"' >> ~/.zshrc
export PATH="~/anaconda3/bin:${PATH}"
conda install pytorch torchvision torchaudio -c pytorch
